// <auto-generated />
namespace MedicalAffairsSample.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FixEduGrants1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixEduGrants1));
        
        string IMigrationMetadata.Id
        {
            get { return "201809131816533_FixEduGrants1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
