// <auto-generated />
namespace MedicalAffairsSample.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddBusinessUnit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddBusinessUnit));
        
        string IMigrationMetadata.Id
        {
            get { return "201809131802468_AddBusinessUnit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
